//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlaskaExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus()
        {
            this.Managers = new HashSet<Manager>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Bus_id { get; set; }
        public string Bus_start_location { get; set; }
        public string Bus_end_location { get; set; }
        public int Bus_total_seat { get; set; }
        public string Bus_coach { get; set; }
        public int Bus_cost_per_seat { get; set; }
        public string Bus_journey_time { get; set; }
        public string Bus_journey_day { get; set; }
        public string Bus_numberplate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manager> Managers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
