//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlaskaExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public string Manager_email { get; set; }
        public string Manager_password { get; set; }
        public string Manager_fullname { get; set; }
        public string Manager_address { get; set; }
        public string Manager_nid { get; set; }
        public string Manager_phone { get; set; }
    }
}
