//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlaskaExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public string Seller_email { get; set; }
        public string Seller_password { get; set; }
        public string Seller_fullname { get; set; }
        public string Seller_address { get; set; }
        public string Seller_nid { get; set; }
        public string Seller_phone { get; set; }
        public string Seller_image { get; set; }
        public string Seller_addedby { get; set; }
    }
}
