//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlaskaExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public string seller_email { get; set; }
        public string seller_password { get; set; }
        public string seller_fullname { get; set; }
        public string seller_address { get; set; }
        public string seller_nid { get; set; }
        public string seller_phone { get; set; }
        public string seller_image { get; set; }
    }
}
