//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlaskaExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public long Ticket_id { get; set; }
        public string Bus_seats { get; set; }
        public long Schedule_id { get; set; }
        public string Customer_email { get; set; }
        public string Seller_email { get; set; }
        public int Total_price { get; set; }
        public string TXN_id { get; set; }
        public int Ticket_state { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
