//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlaskaExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusDetail
    {
        public int busID { get; set; }
        public string busFrom { get; set; }
        public string busTo { get; set; }
        public Nullable<int> totalSeat { get; set; }
        public string busCoach { get; set; }
        public Nullable<int> CostPerSeat { get; set; }
        public string journeyDate { get; set; }
        

        
    }
}
