//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlaskaExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Customer_email { get; set; }
        public string Customer_password { get; set; }
        public string Customer_fullname { get; set; }
        public string Customer_dob { get; set; }
        public string Customer_gender { get; set; }
        public string Customer_address { get; set; }
        public string Customer_phone { get; set; }
        public string Customer_nid { get; set; }
    }
}
