//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlaskaExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int Bus_id { get; set; }
        public Nullable<int> A1 { get; set; }
        public Nullable<int> A2 { get; set; }
        public Nullable<int> B1 { get; set; }
        public Nullable<int> B2 { get; set; }
        public Nullable<int> C1 { get; set; }
        public Nullable<int> C2 { get; set; }
        public Nullable<int> D1 { get; set; }
        public Nullable<int> D2 { get; set; }
        public Nullable<int> E1 { get; set; }
        public Nullable<int> E2 { get; set; }
        public Nullable<int> F1 { get; set; }
        public Nullable<int> F2 { get; set; }
        public Nullable<int> G1 { get; set; }
        public Nullable<int> G2 { get; set; }
        public Nullable<int> H1 { get; set; }
        public Nullable<int> H2 { get; set; }
    }
}
